<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Rack Focus AI Video Prompt Generator | Shot Lab</title><meta name="description" content="Generate Rack Focus camera movement prompts for Seedance, Kling, Runway, Veo, Pika and Luma. Includes examples, use cases, and copy-ready prompts."><link rel="canonical" href="https://shotlab-1qu.pages.dev/camera-movement/rack-focus.html"><link rel="icon" href="../../favicon.svg" type="image/svg+xml"><meta property="og:type" content="website"><meta property="og:site_name" content="Shot Lab"><meta property="og:title" content="Rack Focus AI Video Prompt Generator | Shot Lab"><meta property="og:description" content="Generate Rack Focus camera movement prompts for Seedance, Kling, Runway, Veo, Pika and Luma. Includes examples, use cases, and copy-ready prompts."><meta property="og:url" content="https://shotlab-1qu.pages.dev/camera-movement/rack-focus.html"><meta property="og:image" content="https://shotlab-1qu.pages.dev/og-image.svg"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="Rack Focus AI Video Prompt Generator | Shot Lab"><meta name="twitter:description" content="Generate Rack Focus camera movement prompts for Seedance, Kling, Runway, Veo, Pika and Luma. Includes examples, use cases, and copy-ready prompts."><meta name="twitter:image" content="https://shotlab-1qu.pages.dev/og-image.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../../css/main.css">
<script async src="https://www.googletagmanager.com/gtag/js?id=G-WZ1SZQYXPC"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag("js",new Date());gtag("config","G-WZ1SZQYXPC");</script>
<script type="application/ld+json">{"@context": "https://schema.org", "@type": "WebApplication", "name": "Rack Focus AI Video Prompt Generator", "description": "Generate Rack Focus camera movement prompts for AI video tools.", "url": "https://shotlab-1qu.pages.dev/camera-movement/rack-focus.html", "applicationCategory": "UtilitiesApplication", "operatingSystem": "All", "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"}}</script>
</head>
<body>
<header class="sh"><div class="sh-in"><a href="/" class="sh-brand">SHOT <b>LAB</b></a><nav class="sh-nav" aria-label="Main navigation"><a href="/camera-moves.html">App</a><a href="/ai-video-prompt-guide.html">Guide</a><a href="/camera-movement-glossary.html">Glossary</a></nav><a href="/camera-moves.html" class="sh-cta">Open App &rarr;</a></div></header>
<main class="page-wrap">
<nav class="bc" aria-label="Breadcrumb"><a href="/">Home</a> <span class="bc-sep">/</span> <span>Camera Movements</span> <span class="bc-sep">/</span> <span>Rack Focus</span></nav>
<script type="application/ld+json">{"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{"@type": "ListItem", "position": 1, "name": "Home", "item": "https://shotlab-1qu.pages.dev/"}, {"@type": "ListItem", "position": 2, "name": "Camera Movements"}, {"@type": "ListItem", "position": 3, "name": "Rack Focus"}]}</script>
<div class="page-hero"><p class="page-eyebrow">Focus · Focus Pull</p><h1 class="page-h1">Rack Focus AI Video Prompt Generator</h1>
<p class="page-intro">Generate Rack Focus prompts for Seedance, Kling, Runway, Veo, Pika, and Luma.</p></div>
<div class="sect"><h2 class="sect-h">Try the generator</h2><div class="mini-gen" id="mg-rack-focus">Loading generator...</div><script src="../../data/models.js"></script><script src="../../js/mini-generator.js"></script><script>initMiniGenerator("mg-rack-focus","a rack focus shifting from the foreground to the background","","");</script></div>
<div class="sect"><h2 class="sect-h">What is a Rack Focus?</h2><div class="body-copy"><p>Focus shifts from one plane of depth to another during the shot — from blurred foreground to sharp background, or vice versa. The sharp subject is always the one the audience should watch.</p></div></div>
<div class="sect"><h2 class="sect-h">When to use it</h2><div class="body-copy"><p>Use to redirect attention within a single frame, to reveal a second character, or to build depth in an otherwise static shot.</p></div></div>
<div class="sect"><h2 class="sect-h">Emotional effect</h2><div class="body-copy"><p>Reveals, attention shifts, depth, nuance. The viewer's eye is guided precisely.</p></div></div>
<div class="sect"><h2 class="sect-h">Prompt formula</h2>
<div class="info-card"><p><strong>Base phrase:</strong> <code>a rack focus shifting from the foreground to the background</code></p>
<p style="margin-top:8px"><strong>Full formula:</strong> <code>[Subject] + Camera: a rack focus shifting from the foreground to the background + [Style] + [Lighting] + [Pacing] + [Ratio]</code></p></div></div>
<div class="sect"><h2 class="sect-h">5 copy-ready example prompts</h2><div class="prompt-list"><div class="prompt-item"><div class="pt-label">Drama</div><div class="pt-text">Two characters face to face. One sharp in foreground, the other blurred. Camera: rack focus from foreground to background. Cinematic drama. Practical room lighting. Slow pacing. 16:9.</div><button class="pt-copy">Copy</button></div><div class="prompt-item"><div class="pt-label">Mystery</div><div class="pt-text">A detective's hand holding a photograph, blurred, crime scene sharp behind. Camera: rack focus from hand to background. Noir mystery style. Cold fluorescent. Slow deliberate pacing. 16:9.</div><button class="pt-copy">Copy</button></div><div class="prompt-item"><div class="pt-label">Nature</div><div class="pt-text">A flower sharp in foreground, a butterfly landing behind. Camera: rack focus from flower to butterfly. Natural documentary. Warm diffused outdoor light. Slow gentle pacing. 16:9.</div><button class="pt-copy">Copy</button></div><div class="prompt-item"><div class="pt-label">Product</div><div class="pt-text">A product sharp in foreground, a model behind. Camera: rack focus from product to face. Commercial beauty editorial. Soft diffused studio light. Slow elegant pacing. 1:1.</div><button class="pt-copy">Copy</button></div><div class="prompt-item"><div class="pt-label">Horror</div><div class="pt-text">A child visible in a blurred background mirror, mundane object sharp in foreground. Camera: rack focus from object to the child in the mirror. Atmospheric horror. Warm practical lamplight. Slow unsettling pacing. 16:9.</div><button class="pt-copy">Copy</button></div></div></div>
<div class="sect"><h2 class="sect-h">Common mistakes</h2><div class="body-copy"><ul><li>Not specifying direction — foreground-to-background vs background-to-foreground produce different emotional beats.</li><li>Using with handheld or fast-moving camera — focus pulls need a stable frame.</li><li>Leaving the reveal subject vague.</li></ul></div></div>
<div class="sect"><h2 class="sect-h">Related movements</h2><div class="rel-strip"><a class="rel-pill" href="slow-dolly-in.html">Slow Dolly In</a><a class="rel-pill" href="dutch-angle.html">Dutch Angle</a><span class="rel-pill" style="opacity:.5">Static Shot</span><a class="rel-pill" href="orbit-shot.html">Orbit Shot</a></div></div>
<div class="sect"><h2 class="sect-h">FAQ</h2><div class="faq"><details class="faq-item"><summary class="faq-q">Can AI models actually do a rack focus?<span class="faq-icon">+</span></summary><div class="faq-a">Some can — Kling and Runway show good depth-of-field handling. Including it explicitly increases the chance of the model attempting it.</div></details><details class="faq-item"><summary class="faq-q">How to write it?<span class="faq-icon">+</span></summary><div class="faq-a">Be explicit about both planes: 'rack focus from the sharp foreground hand to the blurred background face, which then snaps to sharp.'</div></details><details class="faq-item"><summary class="faq-q">Rack Focus vs depth of field?<span class="faq-icon">+</span></summary><div class="faq-a">Rack Focus is an active technique. Depth of field is a lens characteristic. Rack Focus uses shallow DOF to allow the focus to move.</div></details></div>
<script type="application/ld+json">{"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": "Can AI models actually do a rack focus?", "acceptedAnswer": {"@type": "Answer", "text": "Some can \u2014 Kling and Runway show good depth-of-field handling. Including it explicitly increases the chance of the model attempting it."}}, {"@type": "Question", "name": "How to write it?", "acceptedAnswer": {"@type": "Answer", "text": "Be explicit about both planes: 'rack focus from the sharp foreground hand to the blurred background face, which then snaps to sharp.'"}}, {"@type": "Question", "name": "Rack Focus vs depth of field?", "acceptedAnswer": {"@type": "Answer", "text": "Rack Focus is an active technique. Depth of field is a lens characteristic. Rack Focus uses shallow DOF to allow the focus to move."}}]}</script></div>
<div class="cta-band"><h2>See all 38 moves with live demos</h2><a href="/camera-moves.html" class="btn-primary">Open Shot Lab &rarr;</a></div>
</main>
<footer class="sf"><div class="sf-in"><div class="sf-links"><a href="/">Home</a><a href="/camera-moves.html">Open App</a><a href="/ai-video-prompt-guide.html">Prompt Guide</a><a href="/camera-movement-glossary.html">Glossary</a><a href="/about.html">About</a><a href="/contact.html">Contact</a><a href="/privacy-policy.html">Privacy Policy</a><a href="/terms.html">Terms</a><a href="https://github.com/Doomania/shotlab" rel="noopener">GitHub</a></div><p class="sf-copy">Shot Lab &middot; <a href="https://shotlab-1qu.pages.dev">shotlab-1qu.pages.dev</a> &middot; runs entirely in your browser. No sign-in.</p></div></footer><div class="toast" id="toast"></div><script>(function(){document.querySelectorAll('.pt-copy').forEach(function(b){b.addEventListener('click',function(){var t=this.closest('.prompt-item').querySelector('.pt-text').textContent;if(navigator.clipboard){navigator.clipboard.writeText(t).then(function(){st('Copied!')}).catch(function(){fb(t)})}else{fb(t)}})});function fb(t){var a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');document.body.removeChild(a);st('Copied!')}function st(m){var e=document.getElementById('toast');if(!e)return;e.textContent=m;e.classList.add('on');clearTimeout(e._t);e._t=setTimeout(function(){e.classList.remove('on')},1400)}})();</script>
</body>
</html>